function [ S ] = loadMovesCmpWindow( S )
    figPosition = get(S.fig, 'position');
    screensize = get( groot, 'Screensize' );
    S.mouvement.showMouv = true;
    if S.mouvement.showMouv
        p = [figPosition(1) figPosition(2)-figPosition(4)/9-80/720 figPosition(3) screensize(4)/9/720];
        S.mouvement.fig = figure(...
            'name', 'Compteur de mouvements', ...
            'numbertitle','off',...
            'color', 'w', ...
            'CloseRequestFcn', [],...
            'MenuBar','none',...
            'ToolBar','none', ...
            'units', 'normalize', ...
            'position', p);
        uicontrol(S.mouvement.fig, ...
            'style', 'text', ...
            'backgroundcolor', 'w', ...
            'HorizontalAlignment', 'left', ...
            'string', [S.nomMouvs{1} ' : '], ...
            'fontsize', 13, ...
            'units', 'normalize', ...
            'position', [0.03 0.55 1 0.3 ]);
        uicontrol(S.mouvement.fig, ...
            'style', 'text', ...
            'backgroundcolor', 'w', ...
            'HorizontalAlignment', 'left', ...
            'string', [S.nomMouvs{2} ' : '], ...
            'fontsize', 13, ...
            'units', 'normalize', ...
            'position', [0.03 0.15 1 0.3 ]);
        uicontrol(S.mouvement.fig, ...
            'style', 'text', ...
            'backgroundcolor', 'w', ...
            'HorizontalAlignment', 'left', ...
            'string', [S.nomMouvs{3} ' : '], ...
            'fontsize', 13, ...
            'units', 'normalize', ...
            'position', [0.50 0.55 1 0.3 ]);
        uicontrol(S.mouvement.fig, ...
            'style', 'text', ...
            'backgroundcolor', 'w', ...
            'HorizontalAlignment', 'left', ...
            'string', [S.nomMouvs{4} ' : '], ...
            'fontsize', 13, ...
            'units', 'normalize', ...
            'position', [0.50 0.15 1 0.3 ]);
        S.mouvement.cmp.up = 0;
        S.mouvement.cmp.down = 0;
        S.mouvement.cmp.right = 0;
        S.mouvement.cmp.left = 0;
        S.mouvement.show.up = uicontrol(S.mouvement.fig, ...
            'style', 'text', ...
            'backgroundcolor', 'w', ...
            'HorizontalAlignment', 'right', ...
            'fontsize', 13, ...
            'units', 'normalize', ...
            'position', [0.40 0.55 0.08 0.3 ]);
        S.mouvement.show.down = uicontrol(S.mouvement.fig, ...
            'style', 'text', ...
            'backgroundcolor', 'w', ...
            'HorizontalAlignment', 'right', ...
            'fontsize', 13, ...
            'units', 'normalize', ...
            'position', [0.40 0.15 0.08 0.3 ]);
        S.mouvement.show.right = uicontrol(S.mouvement.fig, ...
            'style', 'text', ...
            'backgroundcolor', 'w', ...
            'HorizontalAlignment', 'right', ...
            'fontsize', 13, ...
            'units', 'normalize', ...
            'position', [0.90 0.55 0.08 0.3 ]);
        S.mouvement.show.left = uicontrol(S.mouvement.fig, ...
            'style', 'text', ...
            'backgroundcolor', 'w', ...
            'HorizontalAlignment', 'right', ...
            'fontsize', 13, ...
            'units', 'normalize', ...,
            'string', '0',...
            'position', [0.90 0.15 0.08 0.3]);
    end

end

